name: Terraform Plan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  TF_VAR_aws_region: us-east-1
  TF_VAR_project_name: serverless-file-pipeline-tf
  TF_VAR_environment: dev
  TF_VAR_alert_email: ${{ secrets.ALERT_EMAIL }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  terraform-plan:
    name: Terraform Remote Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::354630286254:role/GitHubOIDC_TerraformPlan_ServerlessFilePipelineLab
          aws-region: us-east-1

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Terraform init with remote backend
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -input=false
